CapstoneProject_23620: 
  target: dev
  outputs:
    dev:
      type: bigquery # or your specific database type
      method: service-account
      project: your_gcp_project
      dataset: your_dataset
      threads: 4
      job_execution_timeout_seconds: 3600  # <--- Add this line here
